version: "3.8"

services:
  app:
    image: chatbot
    ports:
      - "3000:80"
    # environment:
    #   - RAILS_MASTER_KEY=<your-master-key>
    env_file:
      - .env
    volumes:
      - .:/rails
